name: multimedia
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.8.2
  - audioread=3.0.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - decorator=5.1.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - imagehash=4.3.1
  - imageio=2.34.0
  - imageio-ffmpeg=0.4.9
  - imath=3.1.11
  - importlib-metadata=7.1.0
  - jasper=4.2.3
  - joblib=1.4.0
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libogg=1.3.4
  - libopenblas=0.3.27
  - libopencv=4.9.0
  - libopenvino=2024.0.0
  - libopenvino-arm-cpu-plugin=2024.0.0
  - libopenvino-auto-batch-plugin=2024.0.0
  - libopenvino-auto-plugin=2024.0.0
  - libopenvino-hetero-plugin=2024.0.0
  - libopenvino-ir-frontend=2024.0.0
  - libopenvino-onnx-frontend=2024.0.0
  - libopenvino-paddle-frontend=2024.0.0
  - libopenvino-pytorch-frontend=2024.0.0
  - libopenvino-tensorflow-frontend=2024.0.0
  - libopenvino-tensorflow-lite-frontend=2024.0.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - librosa=0.10.1
  - libsndfile=1.2.2
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.14.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - llvmlite=0.42.0
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - moviepy=1.0.3
  - mpg123=1.32.6
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - nettle=3.9.1
  - numba=0.59.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.9.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.2.1
  - p11-kit=0.24.1
  - packaging=24.0
  - pcre2=10.43
  - pillow=10.3.0
  - pip=23.3.1
  - pixman=0.43.4
  - platformdirs=4.2.0
  - pooch=1.8.1
  - proglog=0.1.9
  - pthread-stubs=0.4
  - pugixml=1.14
  - py-opencv=4.9.0
  - pycparser=2.22
  - pydub=0.25.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pywavelets=1.5.0
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.2.0
  - soxr=0.1.3
  - soxr-python=0.3.7
  - sqlite=3.41.2
  - svt-av1=2.0.0
  - tabulate=0.9.0
  - tbb=2021.12.0
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - tornado=6.3.3
  - tqdm=4.66.2
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - flask=3.0.3